sudo: required

dist: xenial

language: python

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      env:
        - JOB=lint
      install:
        - pip install -r requirements.txt
        - pip install flake8
      script:
        - flake8 order

    - stage: test
      services:
        - docker
      env:
        - JOB=test_python27
        - IMG=python:2.7
      install:
        - docker pull $IMG
      script:
        - bash tests/docker.sh $IMG

    - stage: test
      services:
        - docker
      env:
        - JOB=test_python37
        - IMG=python:3.7
      install:
        - docker pull $IMG
      script:
        - bash tests/docker.sh $IMG
